/**
 * Woleet signature backend kit
 * This server aims to provide an easy way to sign a hash and proving that you are the corresponding signee on demand by providing two endpoints:    `/identity` let **anyone** verify that you own the private key corresponding to your address.    `/signature` let **you** (and only you) sign a hash.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', '../../src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.WoleetSignatureBackendKit);
    }
}(this, function (expect, WoleetSignatureBackendKit) {
    'use strict';

    let api;

    beforeEach(function () {
        api = new WoleetSignatureBackendKit.DefaultApi();
    });

    describe('DefaultApi', function () {
        describe('identityGet', function () {

            const query = {
                pubKey: '1HZwkjkeaoZfTSaJxDw6aKkxp45agDiEzN',
                leftData: '5qse4648e536rse5bg9487sef684sz'
            };

            it('should call identityGet successfully', function (done) {
                //uncomment below and update the code to test identityGet
                api.identityGet(query.pubKey, query.leftData, done);
            });
        });
        describe('signatureGet', function () {

            const query = {
                pubKey: '1HZwkjkeaoZfTSaJxDw6aKkxp45agDiEzN',
                hashToSign: '2224fa760fe5b392a8de47b3e889b10446e9cb99cce09f8849c9a8f29186f303'
            };

            it('should call signatureGet successfully', function (done) {
                api.signatureGet(query.hashToSign, {pubKey: query.pubKey}, 'a/MNpBokdmdJu9hGMQJcFEdRy6+XUuSCpLYq/xQEVmM=', done);
            });
        });
    });

}));
