/**
 * Woleet signature backend kit
 * This server aims to provide an easy way to sign a hash and proving that you are the corresponding signee on demand by providing two endpoints:    `/identity` let **anyone** verify that you own the private key corresponding to your address.    `/signature` let **you** (and only you) sign a hash.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', '../../src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.WoleetSignatureBackendKit);
    }
}(this, function (expect, WoleetSignatureBackendKit) {
    'use strict';

    let err400;
    let api;

    const {validateSignature, validateIdentity, isHex, isBase64} = require('../../../util');
    const assert = require('assert');

    const query = {
        pubKey: '1HZwkjkeaoZfTSaJxDw6aKkxp45agDiEzN',
        leftData: '5qse4648e536rse5bg9487sef684sz'
    };

    beforeEach(function () {
        api = new WoleetSignatureBackendKit.DefaultApi();
    });

    beforeEach(function () {
        err400 = new WoleetSignatureBackendKit.InlineResponse400Error();
    });

    const getError = (err) => JSON.parse(err.response.text).error;

    describe('InlineResponse400Error', function () {
        it('should create an instance of InlineResponse400Error', function (done) {
            api.identityGet('invalid-pubkey', query.leftData, function (error, response) {
                assert(!response);
                let instance = WoleetSignatureBackendKit.InlineResponse400Error.constructFromObject(getError(error));
                expect(instance).to.be.a(WoleetSignatureBackendKit.InlineResponse400Error);
                assert(instance.type);
                assert(instance.message);
                assert(instance.statusCode);
                assert.equal(instance.statusCode, 400);
                assert.equal(error.status, 400);
                done();
            });
        });

        it('should have the property statusCode (base name: "statusCode")', function (done) {
            api.identityGet('invalid-pubkey', query.leftData, function (error, response) {
                assert(!response);
                let instance = WoleetSignatureBackendKit.InlineResponse400Error.constructFromObject(getError(error));
                expect(instance).to.be.a(WoleetSignatureBackendKit.InlineResponse400Error);
                assert(instance.statusCode);
                done();
            });
        });

        it('should have the property message (base name: "message")', function (done) {
            api.identityGet('invalid-pubkey', query.leftData, function (error, response) {
                assert(!response);
                let instance = WoleetSignatureBackendKit.InlineResponse400Error.constructFromObject(getError(error));
                expect(instance).to.be.a(WoleetSignatureBackendKit.InlineResponse400Error);
                assert(instance);
                assert(instance.message);
                done();
            });
        });

        it('should have the property type (base name: "type")', function (done) {
            api.identityGet('invalid-pubkey', query.leftData, function (error, response) {
                assert(!response);
                let instance = WoleetSignatureBackendKit.InlineResponse400Error.constructFromObject(getError(error));
                expect(instance).to.be.a(WoleetSignatureBackendKit.InlineResponse400Error);
                assert(instance.type);
                done();
            });
        });

    });

}));
