/**
 * Woleet backend kit API
 * The Woleet backend kit API, as exposed by Woleet backend kit's NodeJS server, allows:  - **your backend** (and only yours) to sign some data using its bitcoin identity (as generated during backend kit installation)  - **anyone** to verify that your backend effectively owns its claimed bitcoin address 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WoleetBackendKitApi) {
      root.WoleetBackendKitApi = {};
    }
    root.WoleetBackendKitApi.IdentityResult = factory(root.WoleetBackendKitApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The IdentityResult model module.
   * @module model/IdentityResult
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>IdentityResult</code>.
   * @alias module:model/IdentityResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>IdentityResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdentityResult} obj Optional instance to populate.
   * @return {module:model/IdentityResult} The populated <code>IdentityResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('rightData')) {
        obj['rightData'] = ApiClient.convertToType(data['rightData'], 'String');
      }
      if (data.hasOwnProperty('signature')) {
        obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
      }
    }
    return obj;
  }

  /**
   * The right part of the signed data (generated ramdomly).
   * @member {String} rightData
   */
  exports.prototype['rightData'] = undefined;
  /**
   * The signature of the concatenation of `leftData` and `rightData` using the bitcoin address `pubKey`.
   * @member {String} signature
   */
  exports.prototype['signature'] = undefined;



  return exports;
}));


