/**
 * Woleet signature backend kit
 * This server aims to provide an easy way to sign a hash and proving that you are the corresponding signee on demand by providing two endpoints:    `/identity` let **anyone** verify that you own the private key corresponding to your address.    `/signature` let **you** (and only you) sign a hash.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['ApiClient'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../ApiClient'));
    } else {
        // Browser globals (root is window)
        if (!root.WoleetSignatureBackendKit) {
            root.WoleetSignatureBackendKit = {};
        }
        root.WoleetSignatureBackendKit.SignatureOUT = factory(root.WoleetSignatureBackendKit.ApiClient);
    }
}(this, function (ApiClient) {
    'use strict';


    /**
     * The SignatureOUT model module.
     * @module model/SignatureOUT
     * @version 1.0.0
     */

    /**
     * Constructs a new <code>SignatureOUT</code>.
     * @alias module:model/SignatureOUT
     * @class
     */
    const exports = function () {

    };

    /**
     * Constructs a <code>SignatureOUT</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignatureOUT} obj Optional instance to populate.
     * @return {module:model/SignatureOUT} The populated <code>SignatureOUT</code> instance.
     */
    exports.constructFromObject = function (data, obj) {
        if (data) {
            obj = obj || new exports();

            if (data.hasOwnProperty('pubKey')) {
                obj['pubKey'] = ApiClient.convertToType(data['pubKey'], 'String');
            }
            if (data.hasOwnProperty('signedHash')) {
                obj['signedHash'] = ApiClient.convertToType(data['signedHash'], 'String');
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('identityURL')) {
                obj['identityURL'] = ApiClient.convertToType(data['identityURL'], 'String');
            }
        }
        return obj;
    };

    /**
     * Bitcoin base58 public key used to sign (same as the pubKey parameter, if provided)
     * @member {String} pubKey
     */
    exports.prototype['pubKey'] = undefined;
    /**
     * Same as hashToSign
     * @member {String} signedHash
     */
    exports.prototype['signedHash'] = undefined;
    /**
     * Right part used to sign
     * @member {String} signature
     */
    exports.prototype['signature'] = undefined;
    /**
     * Current server reference for signature validation
     * @member {String} identityURL
     */
    exports.prototype['identityURL'] = undefined;


    return exports;
}));


