/**
 * Woleet signature backend kit
 * This server aims to provide an easy way to sign a hash and proving that you are the corresponding signee on demand by providing two endpoints:    `/identity` let **anyone** verify that you own the private key corresponding to your address.    `/signature` let **you** (and only you) sign a hash.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function (factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['ApiClient', 'model/Error', 'model/IdentityOUT', 'model/InlineResponse200', 'model/InlineResponse2001', 'model/InlineResponse400', 'model/InlineResponse400Error', 'model/SignatureOUT', 'api/DefaultApi'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('./ApiClient'), require('./model/Error'), require('./model/IdentityOUT'), require('./model/InlineResponse200'), require('./model/InlineResponse2001'), require('./model/InlineResponse400'), require('./model/InlineResponse400Error'), require('./model/SignatureOUT'), require('./api/DefaultApi'));
    }
}(function (ApiClient, Error, IdentityOUT, InlineResponse200, InlineResponse2001, InlineResponse400, InlineResponse400Error, SignatureOUT, DefaultApi) {
    'use strict';

    //noinspection UnnecessaryLocalVariableJS
    /**
     * This_server_aims_to_provide_an_easy_way_to_sign_a_hash_and_proving_that_you_are_the_corresponding_signee_on_demand_by_providing_two_endpoints__identity_let_anyone_verify_that_you_own_the_private_key_corresponding_to_your_address___signature_let_you__and_only_you_sign_a_hash_.<br>
     * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
     * <p>
     * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
     * <pre>
     * var WoleetSignatureBackendKit = require('index'); // See note below*.
     * var xxxSvc = new WoleetSignatureBackendKit.XxxApi(); // Allocate the API class we're going to use.
     * var yyyModel = new WoleetSignatureBackendKit.Yyy(); // Construct a model instance.
     * yyyModel.someProperty = 'someValue';
     * ...
     * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
     * ...
     * </pre>
     * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
     * and put the application logic within the callback function.</em>
     * </p>
     * <p>
     * A non-AMD browser application (discouraged) might do something like this:
     * <pre>
     * var xxxSvc = new WoleetSignatureBackendKit.XxxApi(); // Allocate the API class we're going to use.
     * var yyy = new WoleetSignatureBackendKit.Yyy(); // Construct a model instance.
     * yyyModel.someProperty = 'someValue';
     * ...
     * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
     * ...
     * </pre>
     * </p>
     * @module index
     * @version 1.0.0
     */
    const exports = {
        /**
         * The ApiClient constructor.
         * @property {module:ApiClient}
         */
        ApiClient: ApiClient,
        /**
         * The Error model constructor.
         * @property {module:model/Error}
         */
        Error: Error,
        /**
         * The IdentityOUT model constructor.
         * @property {module:model/IdentityOUT}
         */
        IdentityOUT: IdentityOUT,
        /**
         * The InlineResponse200 model constructor.
         * @property {module:model/InlineResponse200}
         */
        InlineResponse200: InlineResponse200,
        /**
         * The InlineResponse2001 model constructor.
         * @property {module:model/InlineResponse2001}
         */
        InlineResponse2001: InlineResponse2001,
        /**
         * The InlineResponse400 model constructor.
         * @property {module:model/InlineResponse400}
         */
        InlineResponse400: InlineResponse400,
        /**
         * The InlineResponse400Error model constructor.
         * @property {module:model/InlineResponse400Error}
         */
        InlineResponse400Error: InlineResponse400Error,
        /**
         * The SignatureOUT model constructor.
         * @property {module:model/SignatureOUT}
         */
        SignatureOUT: SignatureOUT,
        /**
         * The DefaultApi service constructor.
         * @property {module:api/DefaultApi}
         */
        DefaultApi: DefaultApi
    };

    return exports;
}));
